-- RELATÓRIOS

-- TEMPORARY TABLES

CL SCR

CREATE GLOBAL TEMPORARY TABLE RELATORIO (
IDRELATORIO NUMBER(10),
NOME_RELATORIO VARCHAR(50));

DROP TABLE RELATORIO;

INSERT INTO RELATORIO ( IDRELATORIO, NOME_RELATORIO ) VALUES ( 1, 'TESTE RELATORIO 1' );

COMMIT;

SELECT * FROM RELATORIO;

-- RELATORIO NOTA

/* CRIE UM SELECT QUE RETORNE O NÚMERO DA NOTA FISCAL, O NOME DO CLIENTE, A DATA DA NOTA E O VALOR TOTAL. */

SELECT N.NR_NOTA_FISCAL, CLI.NOME_CLIENTE, N.DATA_EMISSAO, ((PN.QTD_VENDIDA * PN.VL_UNITARIO) * (1 - PN.PERC_DESCONTO/100)) AS PRECO_TOTAL
FROM NOTA_FISCAL N INNER JOIN PRODUTOS_NOTA PN
ON N.NR_NOTA_FISCAL = PN.NR_NOTA_FISCAL
INNER JOIN CLIENTE CLI
ON N.IDCLIENTE = CLI.IDCLIENTE;

/* CREATE GLOBAL TEMPORARY TABLE REL_NOTA (NR_NOTA_FISCAL IN NOTA_FISCAL.NR_NOTA_FISCAL%TYPE,
NOME_CLIENTE IN CLIENTE.NOME_CLIENTE%TYPE, */

/* CRIE UMA PROCEDURE CHAMADA GET_TOTAL_NOTA
QUE RECEBA COMO PARÂMETRO O NÚMERO DA NOTA E
GRAVE EM UMA TABELA TEMPORÁRIA O NÚMERO DA NOTA FISCAL,
O NOME DO CLIENTE, A DATA DA NOTA E O VALOR TOTAL DA MESMA. */

CREATE GLOBAL TEMPORARY TABLE REL_NOTA ( NR_NOTA_FISCAL NUMBER,
NOME_CLIENTE VARCHAR(150),
DATA_EMISSAO DATE,
VALOR_TOTAL INTEGER );

DROP TABLE REL_NOTA;

CREATE OR REPLACE PROCEDURE GET_TOTAL_NOTA (NUMERO_NOTA IN INTEGER) IS

NUM_NOTA INTEGER;
NM_CLI VARCHAR(150);
EMISSAO DATE;
TOTAL INTEGER;

BEGIN

SELECT N.NR_NOTA_FISCAL, CLI.NOME_CLIENTE, N.DATA_EMISSAO, ((PN.QTD_VENDIDA * PN.VL_UNITARIO) * (1 - PN.PERC_DESCONTO/100)) AS PRECO_TOTAL
INTO NUM_NOTA, NM_CLI, EMISSAO, TOTAL
FROM NOTA_FISCAL N INNER JOIN PRODUTOS_NOTA PN
ON N.NR_NOTA_FISCAL = PN.NR_NOTA_FISCAL
INNER JOIN CLIENTE CLI
ON N.IDCLIENTE = CLI.IDCLIENTE
WHERE N.NR_NOTA_FISCAL = NUMERO_NOTA;

INSERT INTO REL_NOTA (NR_NOTA_FISCAL, NOME_CLIENTE, DATA_EMISSAO, VALOR_TOTAL)
VALUES (NUMERO_NOTA, NM_CLI, EMISSAO, TOTAL);

END;

EXECUTE GET_TOTAL_NOTA (1);

SELECT * FROM REL_NOTA;