CREATE USER VENDAS IDENTIFIED BY VENDAS;
GRANT CONNECT, RESOURCE TO VENDAS;

CONN VENDAS/VENDAS


CREATE TABLE REPRESENTANTE (
  IDREPRESENTANTE NUMBER(10) NOT NULL,
  NOME_REPRESENTANTE VARCHAR(120) NULL,
  CPF_REPRESENTANTE NUMBER(11) NULL );

ALTER TABLE REPRESENTANTE ADD PRIMARY KEY(IDREPRESENTANTE);

CREATE TABLE PRODUTO (
  IDPRODUTO NUMBER(10) NOT NULL,
  DSPRODUTO VARCHAR(120) NULL,
  DSMARCA VARCHAR(100) NULL);

ALTER TABLE PRODUTO ADD PRIMARY KEY(IDPRODUTO);

CREATE TABLE CLIENTE (
  IDCLIENTE NUMBER(10) NOT NULL,
  NOME_CLIENTE VARCHAR(150) NULL,
  CNPJ_CLIENTE INTEGER NULL,
  RAMO_ATIVIDADE VARCHAR(100) NULL,
  CIDADE VARCHAR(100) NULL,
  ESTADO VARCHAR(50) NULL,
  ENDERECO VARCHAR(200) NULL);

ALTER TABLE CLIENTE ADD PRIMARY KEY(IDCLIENTE);

CREATE TABLE HISTORICO_PRECO (
  IDPRODUTO NUMBER(10) NOT NULL,
  IDHISTORICO NUMBER(10) NOT NULL,
  DATA_ALTERACAO DATE NULL,
  VALOR_PRODUTO NUMBER(10,2) NULL);

ALTER TABLE HISTORICO_PRECO ADD PRIMARY KEY(IDPRODUTO, IDHISTORICO);

CREATE TABLE NOTA_FISCAL (
  NR_NOTA_FISCAL INTEGER NOT NULL,
  IDREPRESENTANTE NUMBER(10) NOT NULL,
  IDCLIENTE NUMBER(10) NOT NULL,
  DATA_EMISSAO DATE NULL,
  TIPO_PAGAMENTO VARCHAR(30) NULL);

ALTER TABLE NOTA_FISCAL ADD PRIMARY KEY(NR_NOTA_FISCAL);

CREATE TABLE PRODUTOS_NOTA (
  IDPRODUTO NUMBER(10) NOT NULL,
  NR_NOTA_FISCAL INTEGER NOT NULL,
  QTD_VENDIDA NUMBER(6) NULL,
  VL_UNITARIO NUMBER(10,2) NULL,
  PERC_DESCONTO NUMBER(3) NULL );

ALTER TABLE PRODUTOS_NOTA ADD PRIMARY KEY(IDPRODUTO, NR_NOTA_FISCAL);

DROP TABLE NOTA_FISCAL

ALTER TABLE PRODUTOS_NOTA ADD FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO);
ALTER TABLE PRODUTOS_NOTA ADD FOREIGN KEY (NR_NOTA_FISCAL) REFERENCES NOTA_FISCAL(NR_NOTA_FISCAL);

ALTER TABLE NOTA_FISCAL ADD FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
ALTER TABLE NOTA_FISCAL ADD FOREIGN KEY (IDREPRESENTANTE) REFERENCES REPRESENTANTE(IDREPRESENTANTE);

ALTER TABLE HISTORICO_PRECO ADD FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO);