/* CRIE UMA PROCEDURE CHAMADA FECHAMENTO_MENSAL QUE RECEBA COMO
PARÂMETRO UM MÊS/ANO E GRAVE EM UMA TABELA OS TOTAIS DE VENDAS
POR AGRUPADOS POR CLIENTE/REPRESENTANTE E PRODUTOS */

-- VERIFICA SE O MÊS/ANO J�? FOI PROCESSADO
-- SOMA AS COMPRAS POR CLIENTE
	-- GRAVA NA TABELA
-- SOMA AS COMPRAS POR REPRESENTANTE
	-- GRAVA NA TABELA

CREATE TABLE FECHAMENTO_CLI (
IDFECHAMENTO_CLI INTEGER(10),
NOME_CLI VARCHAR2(100),
PRODUTO VARCHAR2(100),
QUANTIADE INTEGER(10),
VALOR_TOTAL INTEGER(10),
DATA_COMPRA 
);

CREATE TABLE FECHAMENTO_REP (
IDFECHAMENTO_REP INTEGER(10),
NOME_REP VARCHAR2(100),
PRODUTO VARCHAR2(100),
QUANTIADE INTEGER(10),
VALOR_TOTAL INTEGER(10),
);
------

CREATE OR REPLACE PROCEDURE FECHAMENTO_MENSAL (MES_ANO VARCHAR) IS

CLIENTE VARCHAR(50);
REPRESENTANTE VARCHAR(50);


BEGIN

SELECT C.NOME_CLIENTE, R.NOME_REPRESENTANTE, P.DSPRODUTO, (PN.QTD_VENDIDA * PN.VL_UNITARIO) VALOR_VENDIDO
FROM PRODUTOS_NOTA PN INNER JOIN PRODUTO P
ON PN.IDPRODUTO = P.IDPRODUTO
INNER JOIN NOTA_FISCAL NF
ON PN.NR_NOTA_FISCAL = NF.NR_NOTA_FISCAL
INNER JOIN CLIENTE C
ON C.IDCLIENTE = NF.IDCLIENTE
INNER JOIN REPRESENTANTE R
ON R.IDREPRESENTANTE = NF.IDREPRESENTANTE
WHERE TO_CHAR(NF.DATA_EMISSAO, 'MM/YYYY') = MES_ANO;

INSERT INTO TABELA (E_IDTABELA, E_NOME, E_PRODUTO, E_VALOR, E_QUANTIADE)
VALUES (SELECT MAX(IDTABELA), NOME, VALOR, QUANTIADE);
END;
/

-----------------------------------

SELECT C.NOME_CLIENTE, R.NOME_REPRESENTANTE, P.DSPRODUTO, (PN.QTD_VENDIDA * PN.VL_UNITARIO) VALOR_VENDIDO
FROM PRODUTOS_NOTA PN INNER JOIN PRODUTO P
ON PN.IDPRODUTO = P.IDPRODUTO
INNER JOIN NOTA_FISCAL NF
ON PN.NR_NOTA_FISCAL = NF.NR_NOTA_FISCAL
INNER JOIN CLIENTE C
ON C.IDCLIENTE = NF.IDCLIENTE
INNER JOIN REPRESENTANTE R
ON R.IDREPRESENTANTE = NF.IDREPRESENTANTE
WHERE TO_CHAR(NF.DATA_EMISSAO, 'MM/YYYY') = '03/2018';

SELECT C.NOME_CLIENTE, R.NOME_REPRESENTANTE
FROM CLIENTE C INNER JOIN NOTA_FISCAL NF
ON C.IDCLIENTE = NF.IDCLIENTE
INNER JOIN REPRESENTANTE R
ON R.IDREPRESENTANTE = NF.IDREPRESENTANTE;

exec VALIDADORES.GET_TOTAL_NOTA(1);

SELECT * FROM REL_NOTA;

CL SCR