ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

-- INSERINDO DADOS

-- REPRESENTANTE
INSERT INTO REPRESENTANTE (IDREPRESENTANTE, NOME_REPRESENTANTE, CPF_REPRESENTANTE) VALUES (1, 'Ricardo Almeida', 98799966077);

INSERT INTO REPRESENTANTE (IDREPRESENTANTE, NOME_REPRESENTANTE, CPF_REPRESENTANTE) VALUES (2, 'Mauro Miranda', 43731822059);

INSERT INTO REPRESENTANTE (IDREPRESENTANTE, NOME_REPRESENTANTE, CPF_REPRESENTANTE) VALUES (3, 'Carlos Prado', 89540932050);

INSERT INTO REPRESENTANTE (IDREPRESENTANTE, NOME_REPRESENTANTE, CPF_REPRESENTANTE) VALUES (4, 'João Paulo', 67238676028);

-- PRODUTO
INSERT INTO PRODUTO (IDPRODUTO, DSPRODUTO, DSMARCA) VALUES (1, 'Caneta', 'Bic');

INSERT INTO PRODUTO (IDPRODUTO, DSPRODUTO, DSMARCA) VALUES (2, 'Lápis de Cor', 'Faber Castell');

INSERT INTO PRODUTO (IDPRODUTO, DSPRODUTO, DSMARCA) VALUES (3, 'Canetinha', 'Bic');

INSERT INTO PRODUTO (IDPRODUTO, DSPRODUTO, DSMARCA) VALUES (4, 'Fine Pen', 'Faber Castell');

-- CLIENTE
INSERT INTO CLIENTE (IDCLIENTE, NOME_CLIENTE, CNPJ_CLIENTE, RAMO_ATIVIDADE, CIDADE, ESTADO, ENDERECO)
VALUES (1, 'José Prado', 57892647000192, 'Pedreiro', 'Curitiba', 'Parana', 'Rua dos enguifigalfos, 1212');

INSERT INTO CLIENTE (IDCLIENTE, NOME_CLIENTE, CNPJ_CLIENTE, RAMO_ATIVIDADE, CIDADE, ESTADO, ENDERECO)
VALUES (2, 'André Luiz', 98037953000129, 'Coveiro', 'Curitiba', 'Parana', 'Rua Antonio Maria, 2424');

INSERT INTO CLIENTE (IDCLIENTE, NOME_CLIENTE, CNPJ_CLIENTE, RAMO_ATIVIDADE, CIDADE, ESTADO, ENDERECO)
VALUES (3, 'Carlos Monteiro', 78823563000177, 'Policial', 'Curitiba', 'Parana', 'Avenida Alameda Prado, 32');

INSERT INTO CLIENTE (IDCLIENTE, NOME_CLIENTE, CNPJ_CLIENTE, RAMO_ATIVIDADE, CIDADE, ESTADO, ENDERECO)
VALUES (4, 'Zezé Motta', 96938835000166, 'Espartana', 'Curitiba', 'Parana', 'Rua Morte Lenta, 666');

--NOTA FISCAL
INSERT INTO NOTA_FISCAL (NR_NOTA_FISCAL, IDREPRESENTANTE, IDCLIENTE, DATA_EMISSAO, TIPO_PAGAMENTO)
VALUES (1, 1, 2, '19/03/2018', 'Cartao Debito');

INSERT INTO NOTA_FISCAL (NR_NOTA_FISCAL, IDREPRESENTANTE, IDCLIENTE, DATA_EMISSAO, TIPO_PAGAMENTO)
VALUES (2, 2, 4, '25/01/2018', 'Cartao Debito');

-- PRODUTOS NOTA
INSERT INTO PRODUTOS_NOTA (IDPRODUTO, NR_NOTA_FISCAL, QTD_VENDIDA, VL_UNITARIO, PERC_DESCONTO)
VALUES (1, 1, 1, 12, 2);

INSERT INTO PRODUTOS_NOTA (IDPRODUTO, NR_NOTA_FISCAL, QTD_VENDIDA, VL_UNITARIO, PERC_DESCONTO)
VALUES (3, 2, 1, 20, 3);

SELECT * FROM CLIENTE;