CREATE OR REPLACE TRIGGER VALIDAR_CLIENTE
AFTER INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
    IF VALIDADORES.VALIDACNPJ(:NEW.CNPJ_CLIENTE) != 1
	THEN
	    RAISE_APPLICATION_ERROR(-20000, 'THE BUG IS ON THE TABLE');
	END IF;
END;
/

-- TESTE INSERIR COM CNPJ VÁLIDO
INSERT INTO CLIENTE (IDCLIENTE, NOME_CLIENTE, CNPJ_CLIENTE, RAMO_ATIVIDADE, CIDADE, ESTADO, ENDERECO) VALUES (1, 'Alberto', 95044408000171, 'Informatica', 'Curitiba', 'Parana', 'Rua das Macacas');

-- TESTE INSERIR COM CNPJ INVÁLIDO
INSERT INTO CLIENTE (IDCLIENTE, NOME_CLIENTE, CNPJ_CLIENTE, RAMO_ATIVIDADE, CIDADE, ESTADO, ENDERECO) VALUES (1, 'Alberto', 95044408000888, 'Informatica', 'Curitiba', 'Parana', 'Rua das Macacas');

-- TESTE UPDATE COM CNPJ VÁLIDO
UPDATE CLIENTE SET CNPJ_CLIENTE = 67337693000183 WHERE IDCLIENTE = 1;

-- TESTE UPDATE COM CPF INVÁLIDO
UPDATE CLIENTE SET CNPJ_CLIENTE = 67337893000183 WHERE IDCLIENTE = 2;

----------------------------------------------------------------
CREATE OR REPLACE TRIGGER VALIDAR_REPRESENT
AFTER INSERT OR UPDATE ON REPRESENTANTE
FOR EACH ROW
BEGIN
    IF VALIDADORES.VALIDACPF(:NEW.CPF_REPRESENTANTE) != 1
	THEN
	    RAISE_APPLICATION_ERROR(-20000, 'IRMAO TU TEM QUE DIGITAR UM CPF VALIDO');
	END IF;
END;
/

-- TESTE INSERIR COM CPF VÁLIDO
INSERT INTO REPRESENTANTE (IDREPRESENTANTE, NOME_REPRESENTANTE, CPF_REPRESENTANTE) VALUES (1, 'Joao', 61589644093);

-- TESTE INSERIR COM CPF INVÁLIDO
INSERT INTO REPRESENTANTE (IDREPRESENTANTE, NOME_REPRESENTANTE, CPF_REPRESENTANTE) VALUES (2, 'Carlos', 77789644093);

-- TESTE UPDATE COM CPF VÁLIDO
UPDATE REPRESENTANTE SET CPF_REPRESENTANTE = 83953937090 WHERE IDREPRESENTANTE = 1;

-- TESTE UPDATE COM CPF INVÁLIDO
UPDATE REPRESENTANTE SET CPF_REPRESENTANTE = 83957937090 WHERE IDREPRESENTANTE = 2;